/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Setup Status */
        get: operations["setup_status_api_v1_setup_get"];
        put?: never;
        /** Setup */
        post: operations["setup_api_v1_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Session */
        get: operations["current_session_api_v1_sessions_current_get"];
        put?: never;
        post?: never;
        /** Logout */
        delete: operations["logout_api_v1_sessions_current_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/household": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Household */
        get: operations["get_household_api_v1_household_get"];
        put?: never;
        post?: never;
        /** Delete Household */
        delete: operations["delete_household_api_v1_household_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Invitation */
        post: operations["create_invitation_api_v1_invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Invitation */
        post: operations["accept_invitation_api_v1_invitations_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/caregivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Caregivers */
        get: operations["list_caregivers_api_v1_caregivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/caregivers/current/quick-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quick Actions */
        get: operations["get_quick_actions_api_v1_caregivers_current_quick_actions_get"];
        /** Put Quick Actions */
        put: operations["put_quick_actions_api_v1_caregivers_current_quick_actions_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/caregivers/{caregiver_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Caregiver */
        delete: operations["remove_caregiver_api_v1_caregivers__caregiver_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Device Sessions */
        get: operations["list_device_sessions_api_v1_sessions_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/devices/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Device Session */
        delete: operations["revoke_device_session_api_v1_sessions_devices__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change Password */
        put: operations["change_password_api_v1_sessions_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/piyolog/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Import */
        post: operations["preview_import_api_v1_imports_piyolog_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/piyolog/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Import */
        post: operations["confirm_import_api_v1_imports_piyolog_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/piyolog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Imports */
        get: operations["list_imports_api_v1_imports_piyolog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/piyolog/daily-notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Imported Daily Notes */
        get: operations["list_imported_daily_notes_api_v1_imports_piyolog_daily_notes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/piyolog/{batch_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Import Source */
        delete: operations["delete_import_source_api_v1_imports_piyolog__batch_id__source_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/minilog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Minilog */
        get: operations["export_minilog_api_v1_exports_minilog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/timeline.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Timeline Csv */
        get: operations["export_timeline_csv_api_v1_exports_timeline_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/babies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Babies */
        get: operations["list_babies_api_v1_babies_get"];
        put?: never;
        /** Create Baby */
        post: operations["create_baby_api_v1_babies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/babies/{baby_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Baby */
        put: operations["update_baby_api_v1_babies__baby_id__put"];
        post?: never;
        /** Delete Baby */
        delete: operations["delete_baby_api_v1_babies__baby_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/babies/{baby_id}/profile-picture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile Picture */
        get: operations["get_profile_picture_api_v1_babies__baby_id__profile_picture_get"];
        /** Set Profile Picture */
        put: operations["set_profile_picture_api_v1_babies__baby_id__profile_picture_put"];
        post?: never;
        /** Delete Profile Picture */
        delete: operations["delete_profile_picture_api_v1_babies__baby_id__profile_picture_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/care-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Care Records */
        get: operations["list_care_records_api_v1_care_records_get"];
        put?: never;
        /** Post Care Record */
        post: operations["post_care_record_api_v1_care_records_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/care-records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Care Record */
        get: operations["get_care_record_api_v1_care_records__record_id__get"];
        /** Put Care Record */
        put: operations["put_care_record_api_v1_care_records__record_id__put"];
        post?: never;
        /** Delete Care Record */
        delete: operations["delete_care_record_api_v1_care_records__record_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pull Changes */
        get: operations["pull_changes_api_v1_sync_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BabyCreate */
        BabyCreate: {
            /** Display Name */
            display_name: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Due Date */
            due_date?: string | null;
        };
        /** BabyDeleteRequest */
        BabyDeleteRequest: {
            /** Confirmation */
            confirmation: string;
            /** Export Acknowledged */
            export_acknowledged: boolean;
        };
        /** BabyOut */
        BabyOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Due Date */
            due_date: string | null;
            /**
             * Has Profile Picture
             * @default false
             */
            has_profile_picture: boolean;
            /** Updated At */
            updated_at: number;
        };
        /** BabyUpdate */
        BabyUpdate: {
            /** Display Name */
            display_name: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Due Date */
            due_date?: string | null;
        };
        /** Body_confirm_import_api_v1_imports_piyolog_confirm_post */
        Body_confirm_import_api_v1_imports_piyolog_confirm_post: {
            /**
             * Baby Id
             * Format: uuid
             */
            baby_id: string;
            /** Source Time Zone */
            source_time_zone: string;
            /** File */
            file: string;
            /**
             * Retain Source
             * @default true
             */
            retain_source: boolean;
            /**
             * Replace Modified
             * @default false
             */
            replace_modified: boolean;
        };
        /** Body_preview_import_api_v1_imports_piyolog_preview_post */
        Body_preview_import_api_v1_imports_piyolog_preview_post: {
            /**
             * Baby Id
             * Format: uuid
             */
            baby_id: string;
            /** Source Time Zone */
            source_time_zone: string;
            /** File */
            file: string;
        };
        /** Body_set_profile_picture_api_v1_babies__baby_id__profile_picture_put */
        Body_set_profile_picture_api_v1_babies__baby_id__profile_picture_put: {
            /** Image */
            image: string;
        };
        /** BottleFeedingCreate */
        BottleFeedingCreate: {
            /** Id */
            id?: string | null;
            /**
             * Baby Id
             * Format: uuid
             */
            baby_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Local Offset Minutes */
            local_offset_minutes: number;
            /** Note */
            note?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "bottle_feeding";
            /** Consumed Ml */
            consumed_ml: number;
            /** Offered Ml */
            offered_ml?: number | null;
            /**
             * Contents
             * @enum {string}
             */
            contents: "breast_milk" | "formula" | "mixed" | "other";
        };
        /** BreastfeedingCreate */
        BreastfeedingCreate: {
            /** Id */
            id?: string | null;
            /**
             * Baby Id
             * Format: uuid
             */
            baby_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Local Offset Minutes */
            local_offset_minutes: number;
            /** Note */
            note?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "breastfeeding";
            /** Estimated Amount Ml */
            estimated_amount_ml?: number | null;
            /** Intervals */
            intervals?: components["schemas"]["BreastfeedingIntervalInput"][];
        };
        /** BreastfeedingIntervalInput */
        BreastfeedingIntervalInput: {
            /**
             * Side
             * @enum {string}
             */
            side: "left" | "right";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
        };
        /** CareRecordOut */
        CareRecordOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Baby Id
             * Format: uuid
             */
            baby_id: string;
            record_type: components["schemas"]["RecordType"];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Local Offset Minutes */
            local_offset_minutes: number;
            /** Note */
            note: string | null;
            /** Author Label */
            author_label: string;
            /** Last Modified By Label */
            last_modified_by_label: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Revision */
            revision: number;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** CareRecordPage */
        CareRecordPage: {
            /** Items */
            items: components["schemas"]["CareRecordOut"][];
            /** Next Before */
            next_before?: number | null;
            /** Next Before Id */
            next_before_id?: string | null;
        };
        /** CareRecordUpdate */
        CareRecordUpdate: {
            /** Expected Revision */
            expected_revision: number;
            /** Record */
            record: components["schemas"]["BreastfeedingCreate"] | components["schemas"]["BottleFeedingCreate"] | components["schemas"]["SolidFoodFeedingCreate"] | components["schemas"]["SleepCreate"] | components["schemas"]["DiaperChangeCreate"] | components["schemas"]["PumpingCreate"] | components["schemas"]["MeasurementCreate"] | components["schemas"]["MedicationAdministrationCreate"] | components["schemas"]["NoteCreate"];
        };
        /** CaregiverOut */
        CaregiverOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username Display */
            username_display: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
        };
        /**
         * ClockFormat
         * @enum {string}
         */
        ClockFormat: "12h" | "24h";
        /** DeviceSessionOut */
        DeviceSessionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Device Name */
            device_name: string | null;
            /** Created At */
            created_at: number;
            /** Last Seen At */
            last_seen_at: number;
            /** Expires At */
            expires_at: number;
            /** Current */
            current: boolean;
        };
        /** DiaperChangeCreate */
        DiaperChangeCreate: {
            /** Id */
            id?: string | null;
            /**
             * Baby Id
             * Format: uuid
             */
            baby_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Local Offset Minutes */
            local_offset_minutes: number;
            /** Note */
            note?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "diaper_change";
            /** Is Wet */
            is_wet: boolean;
            /** Is Dirty */
            is_dirty: boolean;
            /** Stool Colour */
            stool_colour?: string | null;
            /** Stool Consistency */
            stool_consistency?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HouseholdDeleteRequest */
        HouseholdDeleteRequest: {
            /** Confirmation */
            confirmation: string;
        };
        /** HouseholdOut */
        HouseholdOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
            /** Time Zone */
            time_zone: string;
            /** Locale */
            locale: string;
            clock_format: components["schemas"]["ClockFormat"];
            measurement_system: components["schemas"]["MeasurementSystem"];
        };
        /** ImportBatchOut */
        ImportBatchOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Baby Id
             * Format: uuid
             */
            baby_id: string;
            /** Source Hash */
            source_hash: string;
            /** Detected Locale */
            detected_locale: string;
            /** Date From */
            date_from: string | null;
            /** Date To */
            date_to: string | null;
            /** Status */
            status: string;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Source Retained */
            source_retained: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ImportedDailyNoteOut */
        ImportedDailyNoteOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Baby Id
             * Format: uuid
             */
            baby_id: string;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Body */
            body: string;
            /** Source Author Text */
            source_author_text: string | null;
            /** Source Line */
            source_line: number | null;
        };
        /** InvitationAccept */
        InvitationAccept: {
            /** Token */
            token: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Password */
            password: string;
            /** Device Name */
            device_name?: string | null;
        };
        /** InvitationCreate */
        InvitationCreate: {
            /** Expires In Hours */
            expires_in_hours?: number | null;
        };
        /** InvitationOut */
        InvitationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Token */
            token: string;
            /** Expires At */
            expires_at: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Device Name */
            device_name?: string | null;
        };
        /** MeasurementCreate */
        MeasurementCreate: {
            /** Id */
            id?: string | null;
            /**
             * Baby Id
             * Format: uuid
             */
            baby_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Local Offset Minutes */
            local_offset_minutes: number;
            /** Note */
            note?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "measurement";
            /**
             * Kind
             * @enum {string}
             */
            kind: "weight" | "height" | "temperature";
            /** Entered Value */
            entered_value: number | string;
            /** Entered Unit */
            entered_unit: string;
        };
        /**
         * MeasurementSystem
         * @enum {string}
         */
        MeasurementSystem: "metric" | "imperial";
        /** MedicationAdministrationCreate */
        MedicationAdministrationCreate: {
            /** Id */
            id?: string | null;
            /**
             * Baby Id
             * Format: uuid
             */
            baby_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Local Offset Minutes */
            local_offset_minutes: number;
            /** Note */
            note?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "medication_administration";
            /** Medicine Name */
            medicine_name: string;
            /** Amount Value */
            amount_value: number | string;
            /** Unit Code */
            unit_code?: string | null;
            /** Custom Unit */
            custom_unit?: string | null;
            /** Route */
            route?: string | null;
        };
        /** NoteCreate */
        NoteCreate: {
            /** Id */
            id?: string | null;
            /**
             * Baby Id
             * Format: uuid
             */
            baby_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Local Offset Minutes */
            local_offset_minutes: number;
            /** Note */
            note?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "note";
            /** Body */
            body: string;
        };
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PiyoLogPreview */
        PiyoLogPreview: {
            /** Source Hash */
            source_hash: string;
            /** Duplicate Import Id */
            duplicate_import_id?: string | null;
            /**
             * Detected Locale
             * @enum {string}
             */
            detected_locale: "en" | "ja";
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Conflicts */
            conflicts?: {
                [key: string]: number;
            };
            /** Unknown Lines */
            unknown_lines: {
                [key: string]: unknown;
            }[];
            /** Warnings */
            warnings: string[];
        };
        /** PumpingCreate */
        PumpingCreate: {
            /** Id */
            id?: string | null;
            /**
             * Baby Id
             * Format: uuid
             */
            baby_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Local Offset Minutes */
            local_offset_minutes: number;
            /** Note */
            note?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "pumping";
            /** Expressed Ml */
            expressed_ml?: number | null;
        };
        /** QuickActionPreferenceInput */
        QuickActionPreferenceInput: {
            record_type: components["schemas"]["RecordType"];
            /**
             * Is Hidden
             * @default false
             */
            is_hidden: boolean;
        };
        /** QuickActionPreferenceOut */
        QuickActionPreferenceOut: {
            record_type: components["schemas"]["RecordType"];
            /**
             * Is Hidden
             * @default false
             */
            is_hidden: boolean;
            /** Position */
            position: number;
        };
        /** QuickActionPreferencesUpdate */
        QuickActionPreferencesUpdate: {
            /** Actions */
            actions?: components["schemas"]["QuickActionPreferenceInput"][];
        };
        /**
         * RecordType
         * @enum {string}
         */
        RecordType: "breastfeeding" | "bottle_feeding" | "solid_food_feeding" | "sleep" | "diaper_change" | "pumping" | "measurement" | "medication_administration" | "note" | "imported_care_record";
        /** SessionOut */
        SessionOut: {
            caregiver: components["schemas"]["CaregiverOut"];
            /** Csrf Token */
            csrf_token: string;
            /** Expires At */
            expires_at: number;
        };
        /** SetupRequest */
        SetupRequest: {
            /** Setup Token */
            setup_token: string;
            /** Household Name */
            household_name: string;
            /** Time Zone */
            time_zone: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Password */
            password: string;
        };
        /** SetupStatus */
        SetupStatus: {
            /** Setup Required */
            setup_required: boolean;
        };
        /** SleepCreate */
        SleepCreate: {
            /** Id */
            id?: string | null;
            /**
             * Baby Id
             * Format: uuid
             */
            baby_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Local Offset Minutes */
            local_offset_minutes: number;
            /** Note */
            note?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "sleep";
        };
        /** SolidFoodFeedingCreate */
        SolidFoodFeedingCreate: {
            /** Id */
            id?: string | null;
            /**
             * Baby Id
             * Format: uuid
             */
            baby_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Ended At */
            ended_at?: string | null;
            /** Local Offset Minutes */
            local_offset_minutes: number;
            /** Note */
            note?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            record_type: "solid_food_feeding";
            /** Foods */
            foods: string;
            /** Amount Value */
            amount_value?: number | string | null;
            /** Amount Unit */
            amount_unit?: string | null;
            /** Reaction Note */
            reaction_note?: string | null;
        };
        /** SyncChangeOut */
        SyncChangeOut: {
            /** Sequence */
            sequence: number;
            /** Entity Kind */
            entity_kind: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Operation */
            operation: string;
            /** Revision */
            revision: number;
        };
        /** SyncPage */
        SyncPage: {
            /** Changes */
            changes: components["schemas"]["SyncChangeOut"][];
            /** Next Cursor */
            next_cursor: number;
            /** Oldest Valid Cursor */
            oldest_valid_cursor: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    setup_status_api_v1_setup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    setup_api_v1_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_session_api_v1_sessions_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_sessions_current_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_household_api_v1_household_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_household_api_v1_household_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HouseholdDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invitation_api_v1_invitations_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invitation_api_v1_invitations_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationAccept"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_caregivers_api_v1_caregivers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaregiverOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quick_actions_api_v1_caregivers_current_quick_actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuickActionPreferenceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_quick_actions_api_v1_caregivers_current_quick_actions_put: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuickActionPreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuickActionPreferenceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_caregiver_api_v1_caregivers__caregiver_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                caregiver_id: string;
            };
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_device_sessions_api_v1_sessions_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_device_session_api_v1_sessions_devices__session_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_sessions_password_put: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_import_api_v1_imports_piyolog_preview_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_import_api_v1_imports_piyolog_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PiyoLogPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_import_api_v1_imports_piyolog_confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_confirm_import_api_v1_imports_piyolog_confirm_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_imports_api_v1_imports_piyolog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_imported_daily_notes_api_v1_imports_piyolog_daily_notes_get: {
        parameters: {
            query: {
                baby_id: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportedDailyNoteOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_import_source_api_v1_imports_piyolog__batch_id__source_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                batch_id: string;
            };
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_minilog_api_v1_exports_minilog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_timeline_csv_api_v1_exports_timeline_csv_get: {
        parameters: {
            query: {
                baby_id: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_babies_api_v1_babies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BabyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_baby_api_v1_babies_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BabyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BabyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_baby_api_v1_babies__baby_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                baby_id: string;
            };
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BabyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BabyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_baby_api_v1_babies__baby_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                baby_id: string;
            };
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BabyDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_picture_api_v1_babies__baby_id__profile_picture_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                baby_id: string;
            };
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_profile_picture_api_v1_babies__baby_id__profile_picture_put: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                baby_id: string;
            };
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_set_profile_picture_api_v1_babies__baby_id__profile_picture_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_picture_api_v1_babies__baby_id__profile_picture_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                baby_id: string;
            };
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_care_records_api_v1_care_records_get: {
        parameters: {
            query: {
                baby_id: string;
                before?: number | null;
                before_id?: string | null;
                record_type?: components["schemas"]["RecordType"][] | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareRecordPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_care_record_api_v1_care_records_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Mutation-ID"?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BreastfeedingCreate"] | components["schemas"]["BottleFeedingCreate"] | components["schemas"]["SolidFoodFeedingCreate"] | components["schemas"]["SleepCreate"] | components["schemas"]["DiaperChangeCreate"] | components["schemas"]["PumpingCreate"] | components["schemas"]["MeasurementCreate"] | components["schemas"]["MedicationAdministrationCreate"] | components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareRecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_care_record_api_v1_care_records__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareRecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_care_record_api_v1_care_records__record_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                record_id: string;
            };
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CareRecordUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareRecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_care_record_api_v1_care_records__record_id__delete: {
        parameters: {
            query: {
                expected_revision: number;
            };
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                record_id: string;
            };
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pull_changes_api_v1_sync_get: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                minilog_session?: string | null;
                minilog_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
