"""create initial schema

Revision ID: 47ccc6557a5e
Revises:
Create Date: 2026-09-09 21:02:19.617562
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "47ccc6557a5e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "babies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("birth_date", sa.String(length=10), nullable=False),
        sa.Column("due_date", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_babies")),
    )
    op.create_index(op.f("ix_babies_display_name"), "babies", ["display_name"], unique=False)
    op.create_table(
        "caregivers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username_normalized", sa.String(length=80), nullable=False),
        sa.Column("username_display", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "CAREGIVER",
                name="caregiverrole",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("identity_erased_at", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_caregivers")),
    )
    op.create_index(
        op.f("ix_caregivers_username_normalized"),
        "caregivers",
        ["username_normalized"],
        unique=True,
    )
    op.create_table(
        "households",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("time_zone", sa.String(length=64), nullable=False),
        sa.Column("locale", sa.String(length=32), nullable=False),
        sa.Column(
            "clock_format",
            sa.Enum(
                "TWELVE_HOUR",
                "TWENTY_FOUR_HOUR",
                name="clockformat",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "measurement_system",
            sa.Enum(
                "METRIC",
                "IMPERIAL",
                name="measurementsystem",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_households")),
    )
    op.create_table(
        "sync_changes",
        sa.Column("sequence", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity_kind", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column(
            "operation",
            sa.Enum(
                "UPSERT", "DELETE", name="syncoperation", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("changed_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("sequence", name=op.f("pk_sync_changes")),
    )
    op.create_index(
        op.f("ix_sync_changes_changed_at"), "sync_changes", ["changed_at"], unique=False
    )
    op.create_index(op.f("ix_sync_changes_entity_id"), "sync_changes", ["entity_id"], unique=False)
    op.create_table(
        "sync_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("oldest_valid_sequence", sa.Integer(), nullable=False),
        sa.Column("last_pruned_at", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_state")),
    )
    op.create_table(
        "baby_profile_pictures",
        sa.Column("baby_id", sa.String(length=36), nullable=False),
        sa.Column("webp_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.CheckConstraint("width = height", name=op.f("ck_baby_profile_pictures_picture_square")),
        sa.ForeignKeyConstraint(
            ["baby_id"],
            ["babies.id"],
            name=op.f("fk_baby_profile_pictures_baby_id_babies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("baby_id", name=op.f("pk_baby_profile_pictures")),
    )
    op.create_table(
        "caregiver_quick_actions",
        sa.Column("caregiver_id", sa.String(length=36), nullable=False),
        sa.Column(
            "record_type",
            sa.Enum(
                "BREASTFEEDING",
                "BOTTLE_FEEDING",
                "SOLID_FOOD_FEEDING",
                "SLEEP",
                "DIAPER_CHANGE",
                "PUMPING",
                "MEASUREMENT",
                "MEDICATION_ADMINISTRATION",
                "NOTE",
                "IMPORTED_CARE_RECORD",
                name="recordtype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "position >= 0", name=op.f("ck_caregiver_quick_actions_position_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["caregiver_id"],
            ["caregivers.id"],
            name=op.f("fk_caregiver_quick_actions_caregiver_id_caregivers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "caregiver_id", "record_type", name=op.f("pk_caregiver_quick_actions")
        ),
        sa.UniqueConstraint("caregiver_id", "position", name="visible_position"),
    )
    op.create_table(
        "import_batches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("baby_id", sa.String(length=36), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("source_time_zone", sa.String(length=64), nullable=False),
        sa.Column("detected_locale", sa.String(length=32), nullable=False),
        sa.Column("detected_platform", sa.String(length=32), nullable=True),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column("date_from", sa.String(length=10), nullable=True),
        sa.Column("date_to", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("report_json", sa.Text(), nullable=False),
        sa.Column("source_contents", sa.LargeBinary(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("source_deleted_at", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["baby_id"],
            ["babies.id"],
            name=op.f("fk_import_batches_baby_id_babies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["caregivers.id"],
            name=op.f("fk_import_batches_created_by_id_caregivers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
        sa.UniqueConstraint("source_hash", name=op.f("uq_import_batches_source_hash")),
    )
    op.create_index(op.f("ix_import_batches_baby_id"), "import_batches", ["baby_id"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "CAREGIVER",
                name="caregiverrole",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.Column("used_at", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["caregivers.id"],
            name=op.f("fk_invitations_created_by_id_caregivers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invitations_token_hash")),
    )
    op.create_table(
        "processed_mutations",
        sa.Column("mutation_id", sa.String(length=36), nullable=False),
        sa.Column("caregiver_id", sa.String(length=36), nullable=False),
        sa.Column("entity_kind", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("result_revision", sa.Integer(), nullable=False),
        sa.Column("processed_at", sa.Integer(), nullable=False),
        sa.Column("replay_result", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["caregiver_id"],
            ["caregivers.id"],
            name=op.f("fk_processed_mutations_caregiver_id_caregivers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("mutation_id", name=op.f("pk_processed_mutations")),
    )
    op.create_index(
        op.f("ix_processed_mutations_processed_at"),
        "processed_mutations",
        ["processed_at"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token_hash", sa.String(length=64), nullable=False),
        sa.Column("caregiver_id", sa.String(length=36), nullable=False),
        sa.Column("device_name", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.Column("revoked_at", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["caregiver_id"],
            ["caregivers.id"],
            name=op.f("fk_sessions_caregiver_id_caregivers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=True)
    op.create_table(
        "care_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("baby_id", sa.String(length=36), nullable=False),
        sa.Column(
            "record_type",
            sa.Enum(
                "BREASTFEEDING",
                "BOTTLE_FEEDING",
                "SOLID_FOOD_FEEDING",
                "SLEEP",
                "DIAPER_CHANGE",
                "PUMPING",
                "MEASUREMENT",
                "MEDICATION_ADMINISTRATION",
                "NOTE",
                "IMPORTED_CARE_RECORD",
                name="recordtype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("occurred_at_utc", sa.Integer(), nullable=False),
        sa.Column("local_offset_minutes", sa.Integer(), nullable=False),
        sa.Column("ended_at_utc", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("author_id", sa.String(length=36), nullable=True),
        sa.Column("author_label", sa.String(length=120), nullable=False),
        sa.Column("last_modified_by_id", sa.String(length=36), nullable=True),
        sa.Column("last_modified_by_label", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.Integer(), nullable=True),
        sa.Column("import_batch_id", sa.String(length=36), nullable=True),
        sa.Column("import_source_line", sa.Integer(), nullable=True),
        sa.Column("modified_since_import", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "ended_at_utc IS NULL OR ended_at_utc >= occurred_at_utc",
            name=op.f("ck_care_records_end_after_start"),
        ),
        sa.CheckConstraint(
            "local_offset_minutes BETWEEN -840 AND 840", name=op.f("ck_care_records_offset_range")
        ),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_care_records_revision_positive")),
        sa.ForeignKeyConstraint(
            ["author_id"], ["caregivers.id"], name=op.f("fk_care_records_author_id_caregivers")
        ),
        sa.ForeignKeyConstraint(
            ["baby_id"],
            ["babies.id"],
            name=op.f("fk_care_records_baby_id_babies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_care_records_import_batch_id_import_batches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["last_modified_by_id"],
            ["caregivers.id"],
            name=op.f("fk_care_records_last_modified_by_id_caregivers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_care_records")),
    )
    op.create_index(op.f("ix_care_records_baby_id"), "care_records", ["baby_id"], unique=False)
    op.create_index(
        op.f("ix_care_records_deleted_at"), "care_records", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_care_records_occurred_at_utc"), "care_records", ["occurred_at_utc"], unique=False
    )
    op.create_index(
        op.f("ix_care_records_record_type"), "care_records", ["record_type"], unique=False
    )
    op.create_index(
        "ix_care_records_timeline",
        "care_records",
        ["baby_id", "deleted_at", "occurred_at_utc", "id"],
        unique=False,
    )
    op.create_index(
        "uq_active_sleep_per_baby",
        "care_records",
        ["baby_id"],
        unique=True,
        sqlite_where=sa.text(
            "record_type = 'SLEEP' AND ended_at_utc IS NULL AND deleted_at IS NULL"
        ),
    )
    op.create_index(
        "uq_active_breastfeeding_per_baby",
        "care_records",
        ["baby_id"],
        unique=True,
        sqlite_where=sa.text(
            "record_type = 'BREASTFEEDING' AND ended_at_utc IS NULL AND deleted_at IS NULL"
        ),
    )
    op.create_index(
        "uq_active_pumping_per_caregiver_baby",
        "care_records",
        ["baby_id", "author_id"],
        unique=True,
        sqlite_where=sa.text(
            "record_type = 'PUMPING' AND ended_at_utc IS NULL AND deleted_at IS NULL"
        ),
    )
    op.create_table(
        "imported_daily_notes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("baby_id", sa.String(length=36), nullable=False),
        sa.Column("local_date", sa.String(length=10), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("source_author_text", sa.String(length=200), nullable=True),
        sa.Column("import_batch_id", sa.String(length=36), nullable=False),
        sa.Column("source_line", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baby_id"],
            ["babies.id"],
            name=op.f("fk_imported_daily_notes_baby_id_babies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_imported_daily_notes_import_batch_id_import_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_imported_daily_notes")),
    )
    op.create_index(
        op.f("ix_imported_daily_notes_baby_id"), "imported_daily_notes", ["baby_id"], unique=False
    )
    op.create_index(
        op.f("ix_imported_daily_notes_import_batch_id"),
        "imported_daily_notes",
        ["import_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_imported_daily_notes_local_date"),
        "imported_daily_notes",
        ["local_date"],
        unique=False,
    )
    op.create_table(
        "bottle_feeding_records",
        sa.Column("care_record_id", sa.String(length=36), nullable=False),
        sa.Column("consumed_ml", sa.Integer(), nullable=False),
        sa.Column("offered_ml", sa.Integer(), nullable=True),
        sa.Column("contents", sa.String(length=24), nullable=False),
        sa.CheckConstraint(
            "consumed_ml >= 0", name=op.f("ck_bottle_feeding_records_consumed_non_negative")
        ),
        sa.CheckConstraint(
            "offered_ml IS NULL OR offered_ml >= consumed_ml",
            name=op.f("ck_bottle_feeding_records_offered_enough"),
        ),
        sa.ForeignKeyConstraint(
            ["care_record_id"],
            ["care_records.id"],
            name=op.f("fk_bottle_feeding_records_care_record_id_care_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("care_record_id", name=op.f("pk_bottle_feeding_records")),
    )
    op.create_table(
        "breastfeeding_intervals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("care_record_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("started_at_utc", sa.Integer(), nullable=False),
        sa.Column("ended_at_utc", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "ended_at_utc IS NULL OR ended_at_utc >= started_at_utc",
            name=op.f("ck_breastfeeding_intervals_end_after_start"),
        ),
        sa.CheckConstraint(
            "position >= 0", name=op.f("ck_breastfeeding_intervals_position_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["care_record_id"],
            ["care_records.id"],
            name=op.f("fk_breastfeeding_intervals_care_record_id_care_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_breastfeeding_intervals")),
        sa.UniqueConstraint(
            "care_record_id", "position", name=op.f("uq_breastfeeding_intervals_care_record_id")
        ),
    )
    op.create_index(
        op.f("ix_breastfeeding_intervals_care_record_id"),
        "breastfeeding_intervals",
        ["care_record_id"],
        unique=False,
    )
    op.create_table(
        "breastfeeding_records",
        sa.Column("care_record_id", sa.String(length=36), nullable=False),
        sa.Column("estimated_amount_ml", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "estimated_amount_ml IS NULL OR estimated_amount_ml >= 0",
            name=op.f("ck_breastfeeding_records_amount_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["care_record_id"],
            ["care_records.id"],
            name=op.f("fk_breastfeeding_records_care_record_id_care_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("care_record_id", name=op.f("pk_breastfeeding_records")),
    )
    op.create_table(
        "diaper_change_records",
        sa.Column("care_record_id", sa.String(length=36), nullable=False),
        sa.Column("is_wet", sa.Boolean(), nullable=False),
        sa.Column("is_dirty", sa.Boolean(), nullable=False),
        sa.Column("stool_colour", sa.String(length=32), nullable=True),
        sa.Column("stool_consistency", sa.String(length=32), nullable=True),
        sa.CheckConstraint(
            "is_dirty = 1 OR (stool_colour IS NULL AND stool_consistency IS NULL)",
            name=op.f("ck_diaper_change_records_stool_requires_dirty"),
        ),
        sa.CheckConstraint(
            "is_wet = 1 OR is_dirty = 1", name=op.f("ck_diaper_change_records_wet_or_dirty")
        ),
        sa.ForeignKeyConstraint(
            ["care_record_id"],
            ["care_records.id"],
            name=op.f("fk_diaper_change_records_care_record_id_care_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("care_record_id", name=op.f("pk_diaper_change_records")),
    )
    op.create_table(
        "imported_care_records",
        sa.Column("care_record_id", sa.String(length=36), nullable=False),
        sa.Column("raw_label", sa.String(length=200), nullable=False),
        sa.Column("raw_details", sa.Text(), nullable=True),
        sa.Column("raw_line", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["care_record_id"],
            ["care_records.id"],
            name=op.f("fk_imported_care_records_care_record_id_care_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("care_record_id", name=op.f("pk_imported_care_records")),
    )
    op.create_table(
        "measurement_records",
        sa.Column("care_record_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("canonical_value", sa.String(length=40), nullable=False),
        sa.Column("canonical_unit", sa.String(length=24), nullable=False),
        sa.Column("entered_value", sa.String(length=40), nullable=False),
        sa.Column("entered_unit", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(
            ["care_record_id"],
            ["care_records.id"],
            name=op.f("fk_measurement_records_care_record_id_care_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("care_record_id", name=op.f("pk_measurement_records")),
    )
    op.create_table(
        "medication_administration_records",
        sa.Column("care_record_id", sa.String(length=36), nullable=False),
        sa.Column("medicine_name", sa.String(length=200), nullable=False),
        sa.Column("amount_value", sa.String(length=40), nullable=False),
        sa.Column("unit_code", sa.String(length=32), nullable=True),
        sa.Column("custom_unit", sa.String(length=40), nullable=True),
        sa.Column("route", sa.String(length=40), nullable=True),
        sa.CheckConstraint(
            "(unit_code IS NULL AND custom_unit IS NOT NULL) OR "
            "(unit_code IS NOT NULL AND custom_unit IS NULL)",
            name=op.f("ck_medication_administration_records_exactly_one_unit"),
        ),
        sa.ForeignKeyConstraint(
            ["care_record_id"],
            ["care_records.id"],
            name=op.f("fk_medication_administration_records_care_record_id_care_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "care_record_id", name=op.f("pk_medication_administration_records")
        ),
    )
    op.create_table(
        "note_records",
        sa.Column("care_record_id", sa.String(length=36), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["care_record_id"],
            ["care_records.id"],
            name=op.f("fk_note_records_care_record_id_care_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("care_record_id", name=op.f("pk_note_records")),
    )
    op.create_table(
        "pumping_records",
        sa.Column("care_record_id", sa.String(length=36), nullable=False),
        sa.Column("expressed_ml", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "expressed_ml IS NULL OR expressed_ml >= 0",
            name=op.f("ck_pumping_records_amount_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["care_record_id"],
            ["care_records.id"],
            name=op.f("fk_pumping_records_care_record_id_care_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("care_record_id", name=op.f("pk_pumping_records")),
    )
    op.create_table(
        "sleep_records",
        sa.Column("care_record_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["care_record_id"],
            ["care_records.id"],
            name=op.f("fk_sleep_records_care_record_id_care_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("care_record_id", name=op.f("pk_sleep_records")),
    )
    op.create_table(
        "solid_food_feeding_records",
        sa.Column("care_record_id", sa.String(length=36), nullable=False),
        sa.Column("foods", sa.Text(), nullable=False),
        sa.Column("amount_value", sa.String(length=40), nullable=True),
        sa.Column("amount_unit", sa.String(length=40), nullable=True),
        sa.Column("reaction_note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(amount_value IS NULL AND amount_unit IS NULL) OR "
            "(amount_value IS NOT NULL AND amount_unit IS NOT NULL)",
            name=op.f("ck_solid_food_feeding_records_amount_complete"),
        ),
        sa.ForeignKeyConstraint(
            ["care_record_id"],
            ["care_records.id"],
            name=op.f("fk_solid_food_feeding_records_care_record_id_care_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("care_record_id", name=op.f("pk_solid_food_feeding_records")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("solid_food_feeding_records")
    op.drop_table("sleep_records")
    op.drop_table("pumping_records")
    op.drop_table("note_records")
    op.drop_table("medication_administration_records")
    op.drop_table("measurement_records")
    op.drop_table("imported_care_records")
    op.drop_table("diaper_change_records")
    op.drop_table("breastfeeding_records")
    op.drop_index(
        op.f("ix_breastfeeding_intervals_care_record_id"), table_name="breastfeeding_intervals"
    )
    op.drop_table("breastfeeding_intervals")
    op.drop_table("bottle_feeding_records")
    op.drop_index(op.f("ix_imported_daily_notes_local_date"), table_name="imported_daily_notes")
    op.drop_index(
        op.f("ix_imported_daily_notes_import_batch_id"), table_name="imported_daily_notes"
    )
    op.drop_index(op.f("ix_imported_daily_notes_baby_id"), table_name="imported_daily_notes")
    op.drop_table("imported_daily_notes")
    op.drop_index("uq_active_pumping_per_caregiver_baby", table_name="care_records")
    op.drop_index("uq_active_breastfeeding_per_baby", table_name="care_records")
    op.drop_index("uq_active_sleep_per_baby", table_name="care_records")
    op.drop_index("ix_care_records_timeline", table_name="care_records")
    op.drop_index(op.f("ix_care_records_record_type"), table_name="care_records")
    op.drop_index(op.f("ix_care_records_occurred_at_utc"), table_name="care_records")
    op.drop_index(op.f("ix_care_records_deleted_at"), table_name="care_records")
    op.drop_index(op.f("ix_care_records_baby_id"), table_name="care_records")
    op.drop_table("care_records")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_processed_mutations_processed_at"), table_name="processed_mutations")
    op.drop_table("processed_mutations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_import_batches_baby_id"), table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_table("caregiver_quick_actions")
    op.drop_table("baby_profile_pictures")
    op.drop_table("sync_state")
    op.drop_index(op.f("ix_sync_changes_entity_id"), table_name="sync_changes")
    op.drop_index(op.f("ix_sync_changes_changed_at"), table_name="sync_changes")
    op.drop_table("sync_changes")
    op.drop_table("households")
    op.drop_index(op.f("ix_caregivers_username_normalized"), table_name="caregivers")
    op.drop_table("caregivers")
    op.drop_index(op.f("ix_babies_display_name"), table_name="babies")
    op.drop_table("babies")
    # ### end Alembic commands ###
